# ENV VARS
export ZSH="$HOME/.oh-my-zsh"
export EDITOR=$(which vim)
export VISUAL=$(which vim)
export ARCHFLAGS="-arch x86_64"
export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:"

# PATH global
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/ngrok/bin:$PATH
export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH

# PATH knot
export PATH=/home/xsteti05/brew/bin:$PATH
export PATH=/home/xsteti05/miniconda3/bin:$PATH
__conda_setup="$('/home/xsteti05/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/home/xsteti05/miniconda3/etc/profile.d/conda.sh" ]; then
             . "/home/xsteti05/miniconda3/etc/profile.d/conda.sh"
        else
            export PATH="/home/xsteti05/miniconda3/bin:$PATH"
        fi  
fi
unset __conda_setup

zstyle ':omz:update' mode auto # auto update
zstyle ':omz:update' frequency 10

ZSH_THEME="awesomepanda"
CASE_SENSITIVE="true"

DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="false"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd.mm.yyyy"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#767676'


# Plugin manager 
source $HOME/.oh-my-zsh/antigen.zsh 
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tom-auger/cmdtime --branch=main
antigen bundle zsh-users/zsh-autosuggestions
antigen apply
rm -f ~/.antigen/.lock

plugins=(
    git
    zsh-navigation-tools
    colored-man-pages
)

source $ZSH/oh-my-zsh.sh

# User configuration
# PROMPT
eval orange='$FG[202]'
eval purple='$FG[098]'
eval yellow='$FG[228]'

# Command return status
local ret_status="%(?:%{$fg_bold[green]%}❯ :%{$fg_bold[red]%}✕ %s)%{$reset_color%}"
PROMPT='%{$fg_bold[green]%}%m%{$reset_color%} [%B%{$orange%}$(date +%H:%M)%{$reset_color%}%b] %{$fg_bold[blue]%}$(git_prompt_info)%}%{$fg_bold[blue]%}%1~%{$reset_color%} ${ret_status} '

# Aliases
source $HOME/.bash_aliases
source $HOME/.bash_functions

